#!/usr/bin/env python3
"""Bake the horizontal editor's hex labels. Requires fontTools (build-time only)."""
from io import BytesIO
from pathlib import Path
import zlib
from fontTools import subset
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont

root = Path(__file__).resolve().parents[2]
source = root / "res/docpdf/fonts/Exo2-Italic[wght].ttf"
font = TTFont(source, recalcTimestamp=False)
font = instantiateVariableFont(font, {"wght": 700}, inplace=True)
names = {
    1: "Furnace Pattern IDs", 2: "Bold Italic", 3: "FurnacePatternIDs-BoldItalic",
    4: "Furnace Pattern IDs Bold Italic", 6: "FurnacePatternIDs-BoldItalic",
    16: "Furnace Pattern IDs", 17: "Bold Italic",
}
for record in list(font["name"].names):
    if record.nameID in names:
        font["name"].setName(names[record.nameID], record.nameID,
                            record.platformID, record.platEncID, record.langID)
options = subset.Options()
options.name_IDs = [0, 1, 2, 3, 4, 5, 6, 13, 14, 16, 17]
options.recalc_timestamp = False
subsetter = subset.Subsetter(options=options)
subsetter.populate(text=" 0123456789ABCDEF?")
subsetter.subset(font)
output = BytesIO()
font.save(output)
data = zlib.compress(output.getvalue(), 9)
header = """// Generated by res/fonts/bake-horizontal-ids.py. Do not edit the byte array.
// Hexadecimal subset of Exo 2 Bold Italic, renamed Furnace Pattern IDs.
// Copyright 2013 The Exo 2 Project Authors (https://github.com/NDISCOVER/Exo-2.0)
// Font licensed under SIL OFL 1.1; see res/docpdf/fonts/OFL_exo2.txt.
#ifndef FURNACE_HORIZONTAL_FONT_H
#define FURNACE_HORIZONTAL_FONT_H

static const unsigned char horizontalIDFont[]={
"""
header += "\n".join("  " + ",".join("0x%02x" % b for b in data[i:i+16]) + ","
                    for i in range(0, len(data), 16))
header += "\n};\n\n#endif\n"
(root / "src/gui/horizontalFont.h").write_text(header)
print("Baked %d bytes (%d compressed)" % (len(output.getvalue()), len(data)))
